name: Tag and Release

on:
  schedule:
    - cron: '0 9 5 */2 *'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      
      - name: 'Tag & Push'
        shell: bash
        run: |
          git config --local user.name "Stefan Schwarz"
          git config --local user.email "Stefan.Schwarz2@infineon.com"
          git tag "v`date +'%Y.%m.%d'`"
  
      - name: 'Push tags to trigger building'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
